namespace: community
name: cockroachdb
version: 0.3.1
readme: README.md
authors:
  - Ansible community
description: CockroachDB collection for Ansible
license_file: LICENSE
tags:
  - database
  - cockroachdb
repository: https://github.com/ansible-collections/community.cockroachdb
documentation: https://github.com/ansible-collections/community.cockroachdb
homepage: https://github.com/ansible-collections/community.cockroachdb
issues: https://github.com/ansible-collections/community.cockroachdb/issues
